---
title: "Question2"
output: pdf_document
---
#Load packages and Data
```{r setup, eval=FALSE, include=FALSE}

rm(list = ls())
gc()

knitr::opts_chunk$set(echo = False)
if(!require("readr")) install.packages("reader")
if(!require("plyr")) install.packages("plyr")
pacman::p_load(c(tidyverse, plyr, readr)

list.files('code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))
list.files('..//Question2/code/', full.names = T, recursive = T) %>% as.list() %>% walk(~source(.))

```
We note that the data is in a format that makes it challenging to load it, therefore, we resort to creating a function that will then be used to import this csv data in the right format.
```{r eval=FALSE}
library(readr)
tbl <-
    list.files(pattern = "C:/Users/gariz/DataScience/Solution/23338784/Question2/data/Forbes/", pattern = "*.csv", full.names = T)

  for(i in 1:length(tbl)) {                              
  assign(paste0("data", i),                                   
         read.csv2(paste0("C:/Users/gariz/DataScience/Solution/23338784/Question2/data/Forbes/",
                   tbl[i])))
  }

library(data.table)
library(magrittr)
filenames = list.files(pattern = "\\.csv$")
lapply(filenames, fread, select = c("names.of", "columns", "I.want")) %>% 
  set_names(filenames) %>% 
  rbindlist(idcol = "origin"

```
 

#Plots for FIN24

```{r pressure, echo=FALSE}
plot(pressure)
```

